#!/usr/bin/env bash
while read -r line; do {
  if [[ "$line" =~ @ ]]; then
    line=$(echo $line | sed 's/^.*g //;s/"//g')
    name=${line%% *}; hex=${line##* }
    rgb="$((16#${hex:1:2}));$((16#${hex:3:2}));$((16#${hex:5:2}))"
    printf "%-10s%s " $name $hex
    echo -e "\x1b[48;2;${rgb}m   \x1b[0m"
  fi
}; done < ../lib/colors.conf
